import { createElement } from 'lwc';
import DollarExchangeRate from 'c/dollarExchangeRate';
import getCurrentDollarExchange from '@salesforce/apex/DollarExchangeRateController.getCurrentDollarExchange';


// Import mock data to send through the wire adapter.
const mockDollar = require("./data/wireAdapter.json");

describe('c-dollar-exchange-rate', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-dollar-exchange-rate', {
            is: DollarExchangeRate
        });

         // Emit mock record into the wired field
         getCurrentDollarExchange.emit(mockDollar);

        document.body.appendChild(element);
        const number = element.shadowRoot.querySelector('lightning-formatted-number');
        //expect(1).toBe(2);

        return Promise.resolve().then(() => {
            expect(number.value.data).toBe('5.00');
        });
    });
});